### ISSUE TITLE
What is 'password' => 'SALESFORCE_PASSWORD AND SECURITY_TOKEN'

### ISSUE THREAD

**Issue by mediacompany** [bjsmasth/php-salesforce-rest-api#6]
can you explain how to get this?

**Comment by bjsmasth** [comment]
SALESFORCE_PASSWORD is the password for your salesforce account
you can get from SECURITY_TOKEN from

 My Settings > Personal  >  Reset My Security Token.

And click on "Reset Security Token".Clicking the button invalidates your existing token. After resetting your token, It will be mail to the user mail ID

I hope this will help.

**Comment by mediacompany** [comment]
thanks u i use rest api directly ;-)
