### ISSUE TITLE
Put the pieces together

### ISSUE THREAD

**Issue by chercka** [bjsmasth/php-salesforce-rest-api#8]
Can you show an example of these parts working together? 

I don't understand in which file to define $options and where to make the $crud->query($query) ? 

Thank you!

**Comment by modir** [comment]
For me the only question is what to do after
`$crud->query($query);`

How do I get the data? Or should it be:
`$data = $crud->query($query);`

The other methods look understandable to me.

**Comment by bjsmasth** [comment]
`$crud->query($query); ` will return the results from salesforce.
